site_name: Miva Layout - API Documentation
site_author: Max Hegler
site_url: 'https://mghweb.github.io/miva-layout/'
repo_url: 'https://github.com/mghweb/miva-layout'
repo_name: 'GitHub'

nav:
  - About: index.md
  - MivaLayout:
    - Class Information: MivaLayout/index.md
    - State Object: MivaLayout/StateObject.md
    - Examples: MivaLayout/examples.md
  - MivaLayoutComponentTree:
    - Overview: MivaLayoutComponentTree/overview.md
    - Properties: MivaLayoutComponentTree/properties.md
    - Methods: MivaLayoutComponentTree/methods.md
  - MivaLayoutComponent:
    - Overview: MivaLayoutComponent/overview.md
    - Properties: MivaLayoutComponent/properties.md
    - Methods: MivaLayoutComponent/methods.md

theme:
  name: material
  feature:
    tabs: true
  palette:
    primary: 'red'
    accent: 'cyan'
  logo:
    icon: 'dashboard'
  favicon: /images/favicon.ico

plugins:
  - search

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.details
  - toc:
        permalink: '#'