site_name: Miva Layout - API Documentation
site_author: Max Hegler
site_url: 'https://mghweb.github.io/miva-layout/'
repo_url: 'https://github.com/mghweb/miva-layout'
repo_name: 'GitHub'

nav:
  - Overview: index.md

theme:
  name: material
  palette:
    primary: 'red'
    accent: 'cyan'
  logo:
    icon: 'import_contacts'
  font: false

plugins:
  - search

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.details
  - toc:
        permalink: '#'