site_name: miva-layout.js - API Documentation
site_author: Max Hegler
site_url: https://mghweb.github.io/miva-layout/
repo_url: https://github.com/mghweb/miva-layout
repo_name: GitHub

nav:
  - About: index.md
  - MivaLayout:
    - Class Information: MivaLayout/index.md
    - State Object: MivaLayout/StateObject.md
    - Examples: MivaLayout/examples.md
  - MivaLayoutComponentTree:
    - Class Information: MivaLayoutComponentTree/index.md
    - Examples: MivaLayoutComponentTree/examples.md
  - MivaLayoutComponent:
    - Class Information: MivaLayoutComponent/index.md
    - Examples: MivaLayoutComponent/examples.md

theme:
  name: material
  feature:
    tabs: true
  palette:
    primary: red
    accent: cyan
  logo:
    icon: dashboard
  favicon: /images/favicon.ico

extra_css:
  - css/type-hint.css

plugins:
  - search

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.details
  - toc:
        permalink: '#'